[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.flake8]
max-line-length = 120
extend-ignore = "W605"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["scry"]
